#! /usr/bin/env bash

# This takes boundary update PDFs converted to text and
# builds a JSON list of boundary objects for each zone.
# It will take more effort to parse the language...

# Usage: listify input_file output_file

FILE=$1
OUTFILE=$2

if [ -z $OUTFILE ]
    then
        OUTFILE=$1.json
fi

echo [ > $OUTFILE

# Zones are represented as XX## and a paragraph of
# text describing their boundaries. Here the zone
# names are used as keys.

sed '/^[A-Z0-9]\{4\}$/s/^/{/; /^{/s/$/:/; s/^$/}/' $FILE |\
    tr '\n' ' ' |\
    sed 's/:}/:"/g; s/}/"},/g;' |\
    sed 's/ {/{"/g; s/:/":/' |\
    sed '/:/s/"}, $//; s/: "}, /":"/g; s/},/},\n/g' |\
    sed 's/. "}/."}/' |\
    grep ^{ >> $OUTFILE

sed -i '$s/},/}/' $OUTFILE

echo ] >> $OUTFILE
